version: 2.1

orbs:
  ruby: circleci/ruby@2.3.1

jobs:
  build:
    macos:
      xcode: "16.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
