# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs the UI tests"
  lane :uitest do
    run_tests(
      project: "SaladSampleApp.xcodeproj",
      devices: ["iPhone 13"],
      testplan: "UITests",
      scheme: "SaladSampleApp",
      result_bundle: true
    )
  end
end
