name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild build test -project SaladSampleApp.xcodeproj -scheme SaladSampleApp -destination "platform=iOS Simulator,name=iPhone 11"
