name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: UI Tests
      env:
        PLATFORM: "iOS Simulator"
        DEVICE: "iPhone 16"
      run: |
        set -o pipefail && xcodebuild -project SaladSampleApp.xcodeproj \
          -scheme SaladSampleApp \
          -testPlan UITests \
          -destination "platform=$PLATFORM,name=$DEVICE" \
          -resultBundlePath "./ResultBundle.xcresult" \
          test | xcpretty
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ResultBundle.xcresult
        path: ./ResultBundle.xcresult
