name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: UI Tests
      run: set -o pipefail && xcodebuild test -project SaladSampleApp.xcodeproj -scheme SaladSampleApp -destination "platform=iOS Simulator,name=iPhone 11" -resultBundlePath "./ResultBundle.xcresult" | xcpretty
    - uses: actions/upload-artifact@v2
      with:
        name: ResultBundle.xcresult
        path: ./ResultBundle.xcresult